In [ ]:
# TODO:
# 4. First multiply with determinant then find inverse

In [109]:
import numpy as np
import sys # For terminating when error
import math # For sqaure root

In [112]:
key = open('keya.txt', 'r').read().strip()
if len(key) == 0:
    print('Key can not be of length 0.')
    sys.exit(1)

if 'a' <= key[0] <= 'z': key = [ord(ch)-ord('a') for ch in key if 'a'<=ch<='z'] # If key is a phrase
else: key = [int(k) for k in key.split()] # If key is a matrix, flattened out

n = int(round(math.sqrt(len(key)))) # Find 'n'
if n*n != len(key):
    print('Key length has to be a perfect square.')
    sys.exit(1)
    
key_arr = np.asarray(key)
key_mat = key_arr.reshape(n, n)
key_mat

array([[ 0,  1,  2],
       [11, 12,  0],
       [25, 18, 23]])

In [113]:
pl_text = open('input.txt', 'r').read().strip()
pl_text_trim = ''
for ch in pl_text:
    if 'a' <= ch <= 'z': pl_text_trim += ch # Ensures only lowercase english chars
pl_text_trim

'speakingofdreamsinafigurativesensethenslowlytalkingaboutitsimpactintheliteralsensethewriterkeepsstressingononeveryimportantpointthatdreamshaveanimportantroletoplayinamericanpoliticsafterallaliberalsocietyisformedonthebasisofonesimaginationtheseimaginationsarearesultofonesfreethoughtswhichcanberelatedtodreamsasdreamingprovidesapictureoftherealworlduncoveringthingswhichotherwisemightnothavebeenpondereduponduetonarrowedandlimitedfreedomofimaginingitmayseemrecklesstoconsiderthepossibilityofturningtodreamstoworkthroughthepoliticalconditionstodaybutignoringthemaltogethermightevenbemorerecklesssaystheauthor'

In [114]:
if len(pl_text_trim)%n != 0:
    pl_text_trim = pl_text_trim + 'x'*( n - (len(pl_text_trim)%n) ) # Append required 'x' to make multiple of n
pl_text_trim

'speakingofdreamsinafigurativesensethenslowlytalkingaboutitsimpactintheliteralsensethewriterkeepsstressingononeveryimportantpointthatdreamshaveanimportantroletoplayinamericanpoliticsafterallaliberalsocietyisformedonthebasisofonesimaginationtheseimaginationsarearesultofonesfreethoughtswhichcanberelatedtodreamsasdreamingprovidesapictureoftherealworlduncoveringthingswhichotherwisemightnothavebeenpondereduponduetonarrowedandlimitedfreedomofimaginingitmayseemrecklesstoconsiderthepossibilityofturningtodreamstoworkthroughthepoliticalconditionstodaybutignoringthemaltogethermightevenbemorerecklesssaystheauthorxx'

In [115]:
pl_text_int = [ord(ch)-ord('a') for ch in pl_text_trim]

In [116]:
ci_text = ''
for i in range(0, len(pl_text_int), n):
    segment = pl_text_int[i:i+n]
    dot_prod = np.dot(key_mat, np.asarray(segment).reshape(n,1)) # Matrix multiplication
    for elem in dot_prod:
        ci_text += chr((elem[0]%26) + ord('a')) # Mod + ASCII add
ci_text

'xogaqaihblnyysmiijviocurjugotxxsuhmfxsugdtktafcmzkadmcjgmijvpayjqehhwbuomxcvcoxsuhmfewdbeksvvzqebkncagzkapywujwnowqyhdubzavevffhmmzozdfwogqziasjqyhdubzavkruvmkllbiwduowmxrrahbaemtpkqtmxchcjbcsmhuvcoswypmgcsppuwfcihhwbeosiuhgiojfmyaigvjugzyhovlgkawugmniowxiqjisxgaavldopacatmbrjhnugpkjfmrbcxdjztabwbusvblzdfwogyidebdiupxmflqcodpfymhqugbnhxezoedccnuzungeifhosshmirukwsmrbalgmvosaqcggtulazaqzijecrsdtydzoeynatydqivnymtbnkeptargjtbeknpkkohomegvzwugifougdwcummqzywgmpcagsntxykluihzsrqqiywedgpecrgtrinzkaunqebdekvyccwvctvxugpphrkvwjeywwroiduzgowxvkwwhdgrqgejhuishmcvdxclosephrctttuldkyjztwohzoegmpcagwqohkrosojhnrvq'

In [117]:
open('cipher.txt', 'w').write(ci_text)

609

In [94]:
## Decrypt

In [125]:
key = open('keya.txt', 'r').read().strip()
if len(key) == 0:
    print('Key can not be of length 0.')
    sys.exit(1)
if 'a' <= key[0] <= 'z': key = [ord(ch)-ord('a') for ch in key if 'a'<=ch<='z']
else: key = [int(k) for k in key.split()]

n = int(round(math.sqrt(len(key))))
key_arr = np.asarray(key)
key_mat = key_arr.reshape(n, n)
key_mat

array([[ 0,  1,  2],
       [11, 12,  0],
       [25, 18, 23]])

In [126]:
key_det = np.linalg.det(key_mat)
determ = int(round(key_det))
if determ == 0:
    print('Key matrix is Singular, Determinant=0.')
    sys.exit(1)

if math.gcd(determ, 26) != 1:
    print('Key_Determinant & 26 are not co-prime. Modulo inverse not possible.')
    sys.exit(1)

key_inv = np.linalg.inv(key_mat)
key_adj = np.around(key_inv*key_det).astype(int, copy=False)

In [127]:
# Copied from GFG : https://www.geeksforgeeks.org/multiplicative-inverse-under-modulo-m/
def modInverse(a, m):
    if m == 1: return 0;
    
    m0 = m
    x, y = 1, 0
    
    while a > 1 :
        q = a // m
        t = m
        
        m = a%m # Euclid's Algo
        a = t
        t = y
        
        y = x - q*y
        x = t
        
    if x < 0: x += m0
        
    return x

In [128]:
# Copied from GFG : https://www.geeksforgeeks.org/multiplicative-inverse-under-modulo-m/
def modI(a, m):
    for num in range(1, m):
        if (a*num)%m == 1:
            return num
    return None

In [138]:
check = determ
if math.gcd(check, 26) != 1:
    print('Key_Determinant & 26 are not co-prime. Modulo inverse not possible.')
else:
    print(modInverse(check,26))
    print(modI(check,26))

1
2


In [144]:
### GFG WALA WRONG FOR NEGATIVE NUMBERS, 
# EG: DETERMINANT : -4
#         AND MOD M=3.
#         CORRECT ANS = 2
#         GFG ANS = 1

In [145]:
key_det_mod_inv = modI(determ, 26)
print(determ, key_det_mod_inv)

key_mod_inv = np.zeros(shape=(n, n), dtype=int)
for i in range(len(key_adj)):
    for j in range(len(key_adj[i])):
        key_mod_inv[i][j] = (key_adj[i][j] * key_det_mod_inv) % 26
key_mod_inv

-457 19


array([[18, 13, 12],
       [ 3, 12,  2],
       [12,  7, 25]])

In [146]:
ci_text = open('cipher.txt', 'r').read().strip()
ci_text_int = [ord(ch)-ord('a') for ch in ci_text]

In [187]:
pl_text = ''
for i in range(0, len(ci_text_int), n):
    segment = ci_text_int[i:i+n]
    dot_prod = np.dot(key_mod_inv, np.asarray(segment).reshape(n,1)) # Matrix multiplication
    for elem in dot_prod:
        pl_text += chr((elem[0]%26) + ord('a')) # Mod + ASCII add
pl_text

'speakingofdreamsinafigurativesensethenslowlytalkingaboutitsimpactintheliteralsensethewriterkeepsstressingononeveryimportantpointthatdreamshaveanimportantroletoplayinamericanpoliticsafterallaliberalsocietyisformedonthebasisofonesimaginationtheseimaginationsarearesultofonesfreethoughtswhichcanberelatedtodreamsasdreamingprovidesapictureoftherealworlduncoveringthingswhichotherwisemightnothavebeenpondereduponduetonarrowedandlimitedfreedomofimaginingitmayseemrecklesstoconsiderthepossibilityofturningtodreamstoworkthroughthepoliticalconditionstodaybutignoringthemaltogethermightevenbemorerecklesssaystheauthorxx'

In [188]:
# Erase trailing 'x', atmost (n-1)
x_trail, i = 0, len(pl_text)-1
while i>=0 and pl_text[i]=='x':
    i -= 1
    x_trail += 1

if x_trail > n-1:
    x_trail = n-1
pl_text = pl_text[:-x_trail]
pl_text

'speakingofdreamsinafigurativesensethenslowlytalkingaboutitsimpactintheliteralsensethewriterkeepsstressingononeveryimportantpointthatdreamshaveanimportantroletoplayinamericanpoliticsafterallaliberalsocietyisformedonthebasisofonesimaginationtheseimaginationsarearesultofonesfreethoughtswhichcanberelatedtodreamsasdreamingprovidesapictureoftherealworlduncoveringthingswhichotherwisemightnothavebeenpondereduponduetonarrowedandlimitedfreedomofimaginingitmayseemrecklesstoconsiderthepossibilityofturningtodreamstoworkthroughthepoliticalconditionstodaybutignoringthemaltogethermightevenbemorerecklesssaystheauthor'